platform:
  - x64

environment:
  CONDA_RECIPE: conda
  CONDA_VERSION: 3

  matrix:
  # Add here environement variables to control the Travis CI build
    - CONDA_PY: 37
    - CONDA_PY: 38
    - CONDA_PY: 39
    - CONDA_PY: 310
    - CONDA_PY: 311

install:
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  - if errorlevel 1 exit 1
  - git clone https://github.com/OpenAlea/appveyor-ci.git appveyor-ci
  - cd appveyor-ci
  - call install.bat
  - conda config --prepend channels fredboudon
  - conda config --prepend channels conda-forge

before_build:
  - call before_build.bat

build_script:
  - call build_script.bat

after_build:
  - call after_build.bat

deploy:
  provider: Script
  on:
    branch: master

before_deploy:
  - call before_deploy.bat

deploy_script:
  - call deploy_script.bat

after_deploy:
  - call after_deploy.bat

on_success:
  - call on_success.bat

on_failure:
  - call on_failure.bat

on_finish:
  - call on_finish.bat
