# ------------------------------
# Build system
# ------------------------------
[build-system]
requires = ["sip>=6.6", "PyQt-builder", "setuptools", "setuptools-scm", "wheel"]
build-backend = "sipbuild.api"

# ------------------------------
# setuptools_scm configuration
# ------------------------------
[tool.setuptools_scm]
fallback_version = "0.0.0.dev0"
version_scheme = "guess-next-dev"
local_scheme = "no-local-version"

# ------------------------------
# SIP project configuration
# ------------------------------
[tool.sip.project]
sip-module = "PyQt5.sip"
sip-files-dir = "sip"

# Optional: version will be injected dynamically by setuptools_scm
version = "1.3.3.dev"

# ------------------------------
# SIP bindings
# ------------------------------
[tool.sip.bindings.PyQGLViewer]
qmake-QT = ["xml", "opengl", "gui", "widgets"]
qmake-CONFIG = ["c++14 ; platform_system == \"Linux\""]

libraries = [
    "QGLViewer ; platform_system != \"Windows\"",
    "QGLViewer2 ; platform_system == \"Windows\"",
    "opengl32 ; platform_system == \"Windows\"",
    "glu32 ; platform_system == \"Windows\"",
    "GLU ; platform_system == \"Linux\""
]

extra-compile-args = [
    "-I${CONDA_PREFIX}/include ; platform_system != \"Windows\"",
    "-I${PREFIX}/include ; platform_system != \"Windows\"",
    "-I${BUILD_PREFIX}/${HOST}/sysroot/usr/include ; platform_system != \"Linux\""
]

extra-link-args = [
    "-L${CONDA_PREFIX}/lib ; platform_system != \"Windows\"",
    "-L${PREFIX}/lib ; platform_system != \"Windows\""
]

tags = ["QGLViewer_2_9_1"]
