 # Specify the build system.
[build-system]
requires = ["sip >=6.0.2, <7", "PyQt-builder >=1.6, <2"]
build-backend = "sipbuild.api"

# Specify the PEP 566 metadata for the project.
[tool.sip.metadata]
name = "PyQGLViewer"
version = "1.3.0"
summary = "Python bindings for the libQGViewer widget"
home-page = "https://github.com/fredboudon/PyQGLViewer"
author = "Frederic Boudon"
author-email = "frederic.boudon@cirad.fr"
license = "GPL v3"
#description-file = "README"
requires-dist = "PyQt5 (>=5.12)"

[tool.sip.bindings.PyQGLViewer]
qmake-QT = ['xml opengl gui widgets']
libraries = ['QGLViewer2','opengl32','glu32']
tags = ['QGLViewer_2_9_1']
#include-dirs=['%CONDA_PREFIX%/Library/include','%PREFIX%/Library/include']
#library-dirs=['%CONDA_PREFIX%/Library/lib','%PREFIX%/Library/lib']
extra-compile-args=['-I%CONDA_PREFIX%/Library/include','-I%PREFIX%/Library/include']
extra-link-args=['-L%CONDA_PREFIX%/Library/lib','-L%PREFIX%/Library/lib']


[tool.sip.project]
sip-module="PyQt5.sip"
abi-version='12'

