name: Building Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    uses: fredboudon/github-action-conda-build/.github/workflows/conda-package-build.yml@main
    secrets:
      token: ${{ secrets.ANACONDA_TOKEN }}
